[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/"
  to = "/storybook/"

[[redirects]]
  from = "/index.html"
  to = "/storybook/"